// Mock API service to simulate backend authentication
//const MOCK_BASE_URL = 'http://localhost:8080/api';

// Simulated delay to mimic network request
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// Mock user database
const MOCK_USERS = {
  changmin: {
    username: 'changmin',
    password: 'testing123',
    email: 'changminlee@gmail.com',
  },
  testuser: {
    username: 'testuser',
    password: 'password123',
    email: 'testuser@example.com',
  },
};

// Generate a mock JWT token
const generateMockToken = (username) => {
  // This is a simplified mock token - in reality, this would be generated by the backend
  const header = btoa(JSON.stringify({ alg: 'HS384' }));
  const payload = btoa(JSON.stringify({
    sub: username,
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 86400, // 24 hours from now
  }));
  const signature = 'YPKi2xfcD5EJdr-B52aFtqorn3l_VPENc0TkibRGRMu_6l7kF-pAwM-z6WAClJnD';
  return `${header}.${payload}.${signature}`;
};

export const mockApi = {
  // Mock login endpoint
  login: async (username, password) => {
    // Simulate network delay
    await delay(500);

    // Check if user exists and password matches
    const user = MOCK_USERS[username];

    if (!user) {
      return {
        success: false,
        message: 'User not found',
      };
    }

    if (user.password !== password) {
      return {
        success: false,
        message: 'Invalid password',
      };
    }

    // Return successful login response matching the API spec
    return {
      success: true,
      message: 'Login successful',
      username: user.username,
      email: user.email,
      token: generateMockToken(user.username),
    };
  },

  // Mock logout endpoint (if needed)
  logout: async () => {
    await delay(200);
    return {
      success: true,
      message: 'Logout successful',
    };
  },

  // Validate token (mock implementation)
  validateToken: (token) => {
    if (!token) return false;

    try {
      // Parse the token payload
      const parts = token.split('.');
      if (parts.length !== 3) return false;

      const payload = JSON.parse(atob(parts[1]));
      const now = Math.floor(Date.now() / 1000);

      // Check if token is expired
      return payload.exp > now;
    } catch (error) {
      return false;
    }
  },
};

