// Mock API service to simulate backend authentication
//const MOCK_BASE_URL = 'http://localhost:8080/api';

// Simulated delay to mimic network request
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// Mock user database
const MOCK_USERS = {
  changmin: {
    username: 'changmin',
    password: 'testing123',
    email: 'changminlee@gmail.com',
  },
  testuser: {
    username: 'testuser',
    password: 'password123',
    email: 'testuser@example.com',
  },
};

// Generate a mock JWT token
const generateMockToken = (username) => {
  // This is a simplified mock token - in reality, this would be generated by the backend
  const header = btoa(JSON.stringify({ alg: 'HS384' }));
  const payload = btoa(JSON.stringify({
    sub: username,
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 86400, // 24 hours from now
  }));
  const signature = 'YPKi2xfcD5EJdr-B52aFtqorn3l_VPENc0TkibRGRMu_6l7kF-pAwM-z6WAClJnD';
  return `${header}.${payload}.${signature}`;
};

const buildRankedMatches = () => ([
  { win: true, result: 'Win', mode: 'Competitive', map: 'King’s Row', scoreFor: 3, scoreAgainst: 2, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
  { win: false, result: 'Loss', mode: 'Competitive', map: 'Circuit Royal', scoreFor: 2, scoreAgainst: 3, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString() },
  { win: true, result: 'Win', mode: 'Competitive', map: 'Lijiang Tower', scoreFor: 2, scoreAgainst: 0, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString() },
  { win: true, result: 'Win', mode: 'Competitive', map: 'New Junk City', scoreFor: 3, scoreAgainst: 1, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
  { win: false, result: 'Loss', mode: 'Competitive', map: 'Esperança', scoreFor: 1, scoreAgainst: 2, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString() },
  { win: true, result: 'Win', mode: 'Competitive', map: 'Ilios', scoreFor: 2, scoreAgainst: 1, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString() },
  { win: false, result: 'Loss', mode: 'Competitive', map: 'Dorado', scoreFor: 2, scoreAgainst: 3, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString() },
  { win: true, result: 'Win', mode: 'Competitive', map: 'Eichenwalde', scoreFor: 3, scoreAgainst: 2, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString() },
  { win: true, result: 'Win', mode: 'Competitive', map: 'Paraiso', scoreFor: 2, scoreAgainst: 1, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString() },
  { win: false, result: 'Loss', mode: 'Competitive', map: 'Numbani', scoreFor: 1, scoreAgainst: 2, playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString() },
]);

export const mockApi = {
  // Mock login endpoint
  login: async (username, password) => {
    // Simulate network delay
    await delay(500);

    // Check if user exists and password matches
    const user = MOCK_USERS[username];

    if (!user) {
      return {
        success: false,
        message: 'User not found',
      };
    }

    if (user.password !== password) {
      return {
        success: false,
        message: 'Invalid password',
      };
    }

    // Return successful login response matching the API spec
    return {
      success: true,
      message: 'Login successful',
      username: user.username,
      email: user.email,
      token: generateMockToken(user.username),
    };
  },

  // Mock logout endpoint (if needed)
  logout: async () => {
    await delay(200);
    return {
      success: true,
      message: 'Logout successful',
    };
  },

  // Validate token (mock implementation)
  validateToken: (token) => {
    if (!token) return false;

    try {
      // Parse the token payload
      const parts = token.split('.');
      if (parts.length !== 3) return false;

      const payload = JSON.parse(atob(parts[1]));
      const now = Math.floor(Date.now() / 1000);

      // Check if token is expired
      return payload.exp > now;
    } catch (error) {
      return false;
    }
  },

  // Mock update profile endpoint
  updateProfile: async (updates, token) => {
    await delay(400);

    if (!token) {
      return {
        success: false,
        message: 'Authentication token is required',
      };
    }

    // Simulate a successful profile update
    return {
      success: true,
      message: 'Profile updated successfully',
      username: updates.username,
      email: updates.email,
    };
  },

  searchOverwatchPlayers: async (name, token) => {
    await delay(300);

    if (!token) {
      return {
        success: false,
        message: 'Authentication token is required',
      };
    }

    return {
      success: true,
      players: [
        {
          playerId: 'Tracer-117',
          displayName: `${name || 'Tracer'}#117`,
          avatar: 'https://static.playoverwatch.com/fake/tracer.png',
        },
        {
          playerId: 'Ana-1985',
          displayName: 'Ana#1985',
          avatar: 'https://static.playoverwatch.com/fake/ana.png',
        },
      ],
    };
  },

  buildHistory: (dps, tank, heals) => ({
    currentSeason: 'Season 16',
    dpsHistory: dps,
    tankHistory: tank,
    healsHistory: heals,
    rankedMatches: buildRankedMatches(),
  }),

  saveOverwatchProfile: async (playerId, token) => {
    await delay(300);

    if (!token) {
      return {
        success: false,
        message: 'Authentication token is required',
      };
    }

    return {
      success: true,
      message: 'Overwatch profile saved.',
      profile: {
        playerId,
        battleTag: playerId,
        displayName: playerId.replace('-', '#'),
        avatarUrl: 'https://static.playoverwatch.com/fake/profile.png',
        lastUpdatedAt: new Date().toISOString(),
        gamesWon: 186,
        gamesPlayed: 312,
        winrate: 59.6,
        kda: 3.4,
        damage: 912340,
        healing: 128400,
        dpsRating: 2844,
        tankRating: 2712,
        healsRating: 2905,
        dpsPeakRating: 2950,
        tankPeakRating: 2780,
        healsPeakRating: 2920,
        rankedMatches: buildRankedMatches(),
      },
    };
  },

  getOverwatchProfile: async (token) => {
    await delay(200);

    if (!token) {
      return {
        success: false,
        message: 'Authentication token is required',
      };
    }

    return {
      success: true,
      profile: {
        playerId: 'Tracer-117',
        battleTag: 'Tracer-117',
        displayName: 'Tracer#117',
        avatarUrl: 'https://static.playoverwatch.com/fake/profile.png',
        lastUpdatedAt: new Date().toISOString(),
        gamesWon: 186,
        gamesPlayed: 312,
        winrate: 59.6,
        kda: 3.4,
        damage: 912340,
        healing: 128400,
        dpsRating: 2844,
        tankRating: 2712,
        healsRating: 2905,
        dpsPeakRating: 2950,
        tankPeakRating: 2780,
        healsPeakRating: 2920,
        rankedMatches: buildRankedMatches(),
      },
    };
  },

  getOverwatchHistory:async (token, playerId) => {
    await delay(220);

    if (!token) {
      return {
        success: false,
        message: 'Authentication token is required',
      };
    }

    return {
      success: true,
      history: {
        username: 'testuser',
        playerId: playerId || 'Tracer-117',
        battleTag: playerId || 'Tracer-117',
        displayName: 'Tracer#117',
        avatarUrl: 'https://static.playoverwatch.com/fake/profile.png',
        lastUpdatedAt: new Date().toISOString(),
        currentSeason: 'Season 16',
        dpsRating: 2844,
        tankRating: 2712,
        healsRating: 2905,
        dpsPeakRating: 2950,
        tankPeakRating: 2780,
        healsPeakRating: 2920,
        dpsHistory: [
          { label: 'Apr 28', rating: 2740 },
          { label: 'May 2',  rating: 2800 },
          { label: 'May 5',  rating: 2950 },
          { label: 'May 8',  rating: 2870 },
          { label: 'May 11', rating: 2820 },
          { label: 'May 14', rating: 2860 },
          { label: 'May 17', rating: 2844 },
        ],
        tankHistory: [
          { label: 'Apr 28', rating: 2640 },
          { label: 'May 2',  rating: 2670 },
          { label: 'May 5',  rating: 2695 },
          { label: 'May 8',  rating: 2710 },
          { label: 'May 11', rating: 2780 },
          { label: 'May 14', rating: 2740 },
          { label: 'May 17', rating: 2712 },
        ],
        healsHistory: [
          { label: 'Apr 28', rating: 2790 },
          { label: 'May 2',  rating: 2820 },
          { label: 'May 5',  rating: 2855 },
          { label: 'May 8',  rating: 2900 },
          { label: 'May 11', rating: 2880 },
          { label: 'May 14', rating: 2920 },
          { label: 'May 17', rating: 2905 },
        ],
        dpsSeasonHistory: [
          { label: 'Season 12', rating: 2530 },
          { label: 'Season 13', rating: 2620 },
          { label: 'Season 14', rating: 2700 },
          { label: 'Season 15', rating: 2780 },
          { label: 'Season 16', rating: 2844 },
        ],
        tankSeasonHistory: [
          { label: 'Season 12', rating: 2450 },
          { label: 'Season 13', rating: 2520 },
          { label: 'Season 15', rating: 2650 },
          { label: 'Season 16', rating: 2712 },
        ],
        healsSeasonHistory: [
          { label: 'Season 12', rating: 2610 },
          { label: 'Season 13', rating: 2700 },
          { label: 'Season 14', rating: 2780 },
          { label: 'Season 15', rating: 2860 },
          { label: 'Season 16', rating: 2905 },
        ],
        rankedMatches: buildRankedMatches(),
      },
    };
  },

  getOverwatchLeaderboard: async (token) => {
    await delay(200);

    if (!token) {
      return {
        success: false,
        message: 'Authentication token is required',
      };
    }

    return {
      success: true,
      leaderboard: [
        {
          username: 'testuser',
          playerId: 'Tracer-117',
          displayName: 'Tracer#117',
          gamesWon: 186,
          winrate: 59.6,
          dpsRating: 2844,
          tankRating: 2712,
          healsRating: 2905,
        },
        {
          username: 'changmin',
          playerId: 'Reinhardt-4242',
          displayName: 'Reinhardt#4242',
          gamesWon: 161,
          winrate: 57.2,
          dpsRating: 2670,
          tankRating: 2898,
          healsRating: 2510,
        },
        {
          username: 'fitz',
          playerId: 'Lucio-808',
          displayName: 'Lucio#808',
          gamesWon: 144,
          winrate: 61.1,
          dpsRating: 2722,
          tankRating: 2584,
          healsRating: 2944,
        },
      ],
    };
  },
};

